name: Access Issue Properties

on:
    workflow_dispatch:

jobs:
  access-issue-props:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set issue number
        id: set-issue-number
        run: |
          ISSUE_NUMBER=75          
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV

      - name: Get an issue by number and set issue as output
        if: env.ISSUE_NUMBER 
        id: issue
        env:
            ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
        run: |
            ISSUE=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER
            )
            echo "ISSUE=$(echo $ISSUE | jq -c .)" >> $GITHUB_ENV

      - name: Process issue with JavaScript
        if: env.ISSUE
        id: process-issue
        env:
            ISSUE: ${{ env.ISSUE }}
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.REPO_SECRET }}
            script: |
                const issue = JSON.parse(process.env.ISSUE);
                console.log(issue);
            
     

