name: Access Issue Properties

on:
    workflow_dispatch:

jobs:
  access-issue-props:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set issue number
        id: set-issue
        run: |
          ISSUE_NUMBER=75          
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV

      - name: Get issue by number
        if: env.ISSUE_NUMBER 
        id: issue
        env:
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
          GH_TOKEN: ${{ secrets.REPO_SECRET }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"
          issue=$(gh issue view $ISSUE_NUMBER --json number,title,body,labels,assignees,milestone)
          echo "Issue: $issue"

          # Set outputs
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_OUTPUT
          echo "labels=$(echo $issue | jq -r '.labels | map(.name) | join(",")')" >> $GITHUB_OUTPUT

      - name: Print outputs
        run: |
          echo "Issue number: ${{ steps.issue.outputs.issue_number }}"
          echo "Labels: ${{ steps.issue.outputs.labels }}"