name: Access Issue Properties

on:
    workflow_dispatch:

jobs:
  access-issue-props:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set issue number
        id: set-issue
        run: |
          ISSUE_NUMBER=75          
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV

      - name: Get issue by number
        if: env.ISSUE_NUMBER 
        id: issue
        env:
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"
          issue=$(gh issue view $ISSUE_NUMBER --json number,title,body,labels,assignees,milestone)
          echo "Issue: $issue"
