name: Dump Github Context

on:
    push:
        branches: [ main ]
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main

jobs:
    github-context-job:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump Github Context
                run: echo '${{ toJSON(github) }}' | jq
            
            -   name: Dump Github Actions Context
                run: echo '${{ toJSON(github.event) }}' | jq
