name: Expose API

on:
    workflow_dispatch:


jobs:
    expose-api:
        runs-on: ubuntu-latest
        steps:
          - name: Get Token
            id: get_workflow_token
            uses: peter-murray/workflow-application-token-action@v3
            with:
              application_id: ${{ vars.APP_ID }}
              application_private_key: ${{ secrets.TECKNOB_APP }}
    
          - name: Move PR to Review
            uses: actions/github-script@v7
            # env:
            #   GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
            with:
              github-token: ${{ steps.get_workflow_token.outputs.token }}
              script: |
                console.log("GITHUB_TOKEN: ", process.env.GITHUB_TOKEN);
                # fetch("https://api.github.com/graphql", {
                #   headers: {
                #     "Authorization": `Token ${process.env.GITHUB_TOKEN}`,
                #   },
                # }).then(res => res.json()).then(res => {
                #   console.log(res);
                # });
