name: Expose API

on:
    workflow_dispatch:


jobs:
    expose-api:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Context
              run: echo '${{ toJSON(github) }}' | jq

            - name: Expose API
              run: |
               graphql_api=$(curl -L \
                -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"query": "query { repository(name: \"tecknob\", owner: \"taslim-a-hussain\") { name } }"}' \
                https://api.github.com/graphql \
               )

               echo "API: $graphql_api"
