name: Expose API

on:
    workflow_dispatch:


jobs:
    expose-api:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Context
              run: echo '${{ toJSON(github) }}' | jq

            - name: GitHub Script Testing
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.REPO_SECRET }}
                script: |
                  const outputter = require(".github/scripts/expose-api.js");

                  outputter("Hello World to outputter");
        
