name: Expose API

on:
    workflow_dispatch:


jobs:
    expose-api:
        runs-on: ubuntu-latest
        steps:
            - name: Expose GitHub GraphQL API
              run: |
                  echo "${{ toJson(github) }}" | jq

        
