name: Greetings

on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.REPO_SECRET }}
        issue-message: 'Message that will be displayed on users first issue :smiley:'
        pr-message: 'Message that will be displayed on users first pr :smiley:'
