name: Issue Props Access

on:
    # manual trigger
    workflow_dispatch:

jobs:
    access-issue-props:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Access issue props
                id: get-issue-details
                uses: actions/github-script@v6
                with:
                    github-token: ${{ secrets.REPO_SECRET }}
                    script: |
                        const issueNumber = 75;
                        const issue = await github.rest.issues.get({
                            ...context.repo,
                            issue_number: issueNumber
                        });
                        return issue.data;

            -   name: Print issue props
                if: steps.get-issue-details.outcome
                id: print-issue
                env:
                    ISSUE_NUMBER: ${{ steps.get-issue-details.outcome.issue_number }}
                    ISSUE_TITLE: ${{ steps.get-issue-details.outcome.title }}
                    ISSUE_STATE: ${{ steps.get-issue-details.outcome.state }}
                    ISSUE_BODY: ${{ steps.get-issue-details.outcome.body }}
                    ISSUE_URL: ${{ steps.get-issue-details.outcome.html_url }}
                    ISSUE_LABELS: ${{ steps.get-issue-details.outcome.labels }}
                    ISSUE_ASSIGNEES: ${{ steps.get-issue-details.outcome.assignees }}
                    ISSUE_MILESTONE: ${{ steps.get-issue-details.outcome.milestone }}
                run: |
                    echo "Issue number: $ISSUE_NUMBER"
                    echo "Issue title: $ISSUE_TITLE"
                    echo "Issue state: $ISSUE_STATE"
                    echo "Issue body: $ISSUE_BODY"
                    echo "Issue url: $ISSUE_URL"
                    echo "Issue labels: $ISSUE_LABELS"
                    echo "Issue assignees: $ISSUE_ASSIGNEES"
                    echo "Issue milestone: $ISSUE_MILESTONE"