name: Issue Comment

on:
    issues:
        types: [opened]

jobs:
    comment-on-issue:
        runs-on: ubuntu-latest
        steps:
            -   name: Comment on issue
                uses: peter-evans/create-or-update-comment@v4
                with:
                    token: ${{ secrets.REPO_SECRET }}
                    issue-number: ${{ github.event.issue.number }}
                    body: |
                        Thank you for creating this issue.
                        :smiley:

                    reactions: '+1'
                

