name: Issue Props Access

on:
    # manual trigger
    workflow_dispatch:

jobs:
    access-issue-props:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Access issue props
                id: get-issue-details
                uses: actions/github-script@v6
                with:
                    github-token: ${{ secrets.REPO_SECRET }}
                    script: |
                        const issueNumber = parseInt("${{ 75 }}", 10);
                        const issue = await github.rest.issues.get({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: issueNumber
                        });

                        return issue.data;

            -   name: Print issue details
                run: |
                    echo "details: ${{ steps.get-issue-details }}
