name: Issue Comment

on:
    issues:
        types: [opened]

jobs:
    comment-on-issue:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump Github Context
                run: echo '${{ toJSON(github) }}' | jq
                shell: bash

            -   name: Dump Github Actions Context
                run: echo '${{ toJSON(github.event) }}' | jq
                shell: bash
