name: Issue Props Access

on:
    # manual trigger
    workflow_dispatch:

jobs:
    access-issue-props:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Access issue props
                id: get-issue-details
                uses: actions/github-script@v6
                with:
                    github-token: ${{ secrets.REPO_SECRET }}
                    script: |
                        const issueNumber = 75;
                        const issue = await github.rest.issues.get({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: issueNumber
                        });

                        return issue.data;

            -   name: Print issue details
                run: |
                    echo "Issue number: ${{ steps.get-issue-details.outputs.result.issue_number }}"
                    echo "Issue title: ${{ steps.get-issue-details.outputs.result.title }}"
                    echo "Issue body: ${{ steps.get-issue-details.outputs.result.body }}"
                    echo "Issue labels: ${{ steps.get-issue-details.outputs.result.labels }}"
                    echo "Issue assignees: ${{ steps.get-issue-details.outputs.result.assignees }}"
                    echo "Issue milestone: ${{ steps.get-issue-details.outputs.result.milestone }}"
                    echo "Issue state: ${{ steps.get-issue-details.outputs.result.state }}"
                    echo "Issue created_at: ${{ steps.get-issue-details.outputs.result.created_at }}"
                    echo "Issue updated_at: ${{ steps.get-issue-details.outputs.result.updated_at }}"
                    echo "Issue closed_at: ${{ steps.get-issue-details.outputs.result.closed_at }}"