name: Issue Properties

on:
  workflow_dispatch:

jobs:
  issue-props:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get issue details
        id: get-issue-details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_SECRET }}
          script: |
            const issueNumber = 75;  
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            console.log('issue.data: ', issue.data);

            core.setOutput('issue_number', issue.data.number);
            core.setOutput('title', issue.data.title);
            core.setOutput('body', issue.data.body);
            core.setOutput('labels', issue.data.labels.map(label => label.name).join(', '));
            core.setOutput('assignees', issue.data.assignees.map(assignee => assignee.login).join(', '));
            core.setOutput('milestone', issue.data.milestone ? issue.data.milestone.title : '');
            
      - name: Dump issue details
        run: |
          echo "Dumped issue details: ${{ toJSON(steps.get-issue-details) }}"
          echo "Dumped issue details.outputs: ${{ toJSON(steps.get-issue-details.outputs) }}"

      - name: Print issue details
        run: |
          echo "Issue number: ${{ steps.get-issue-details.outputs.issue_number }}"
          echo "Issue title: ${{ steps.get-issue-details.outputs.title }}"
          echo "Issue body: ${{ steps.get-issue-details.outputs.body }}"
          echo "Issue labels: ${{ steps.get-issue-details.outputs.labels }}"
          echo "Issue assignees: ${{ steps.get-issue-details.outputs.assignees }}"
          echo "Issue milestone: ${{ steps.get-issue-details.outputs.milestone }}"
        

