name: PR Issue Number

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  pr-issue-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue number from PR
        id: extract-issue
        run: |
          issue_number=$(echo "${{ github.event.pull_request.title }}${{ github.event.pull_request.body }}" | grep -oP '(?<=#)\d+' | head -1)
          echo "ISSUE_NUMBER=${issue_number}" >> $GITHUB_ENV

      - name: Print issue number
        if: env.ISSUE_NUMBER
        id: print-issue
        env:
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"

