name: Apply Issue Labels to Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  apply-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract issue number
        id: extract-issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')
          echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"

      - name: Check if issue number is found
        if: steps.extract-issue.outputs.ISSUE_NUMBER != ''
        run: | 
         echo "Found issue number: ${{ steps.extract-issue.outputs.ISSUE_NUMBER }}"
 
      - name: Get labels from issue
        id: get-labels
        if: steps.extract-issue.outputs.ISSUE_NUMBER != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_SECRET }}
          script: |
            const issueNumber = ${{ steps.extract-issue.outputs.ISSUE_NUMBER }};
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            return issue.data.labels.map(label => label.name);

      - name: Apply labels to pull request
        if: steps.extract-issue.outputs.ISSUE_NUMBER != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_SECRET }}
          script: |
            const prNumber = context.issue.number;
            const labels = ${{ steps.get-labels.outputs.result }};
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: labels
              });
            }


