name: PR Issue Number

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  pr-issue-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract issue number from PR
        run: |
            echo "Issue number: $ISSUE_NUMBER"
        env:
            ISSUE_NUMBER: $(echo "${{ github.event.pull_request.title }}${{ github.event.pull_request.body }}" | grep -oP '(?<=#)\d+')
