name: PR Issue Number

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  pr-issue-number:
    runs-on: ubuntu-latest

    env:
      ISSUE_NUMBER:
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract issue number from PR - Print
        run: |
            issue_number=$(echo "${{ github.event.pull_request.title }}${{ github.event.pull_request.body }}" | grep -oP '(?<=#)\d+')"
            echo "ISSUE_NUMBER=${issue_number}" >> $GITHUB_ENV

      - name: Print issue number
        run: |
            echo "Issue number: ${{ env.ISSUE_NUMBER }}"
